### PR TITLE
Gracefully handle `window` global variable

### PR DESCRIPTION
**Pull request by ryancwalsh**
See https://github.com/near/near-api-js/issues/747

All 19 tests in `yarn test` pass.

And my Gatsby project that uses near-api-js now builds too.

### CODE REVIEW

**Comment by volovyk-s** [comment]
@MaximusHaximus can it be a breaking change for any web app?

**Comment by MaximusHaximus** [comment]
> @MaximusHaximus can it be a breaking change for any web app?

I don't think so, but although this changeset may make the code execute without throwing a hard error due to the invalid reference, it also makes the code fail to work in unexpected ways rather than throwing a hard error if someone were to try to use it in the wrong context.  The code that relies on `window` cannot function correctly without a browser context, and the code that relies on `Buffer` cannot function correctly without a real Buffer object implementation existing -- working around the error and providing 'fake' values for the browser's local storage and window objects just means the code will not throw a hard error when you try to use it -- the logic that exists in this PR doesn't make the object _actually function correctly_ in the wrong context.

The key thing to understand is that _you can't use a `WalletConnectedAccount` in the backend/nodeJS context_ -- the _entire purpose_ of this object is to interact with the Wallet _by way of being run inside a web browser_.  'Fixing' this problem actually just hides from the user that they are trying to use an object in a context where it will never work.  The confusing part here is that NAJ contains code that is designed to run in totally different contexts.

To fix this problem _properly_, we need to give the user the ability to know which code will run in which context based on the package that it is part of, and give them an easy way to import only the code that is relevant in the context that they are bundling it for.  

At a high level, this means that we will need to put all code that is **not** context-agnostic into a package named e.g. `near-api-js-core`.  If someone imports this package into _any_ JS environment, the code will work there.  However, any code that is designed to only work in the browser should be shipped as `near-api-js-browser` and code that is designed to only work in the nodeJS context should be shipped as `near-api-js-node`.  Both the `browser` and `node` packages would depend on  the `core` package.  I'm working on a detailed proposal for this style of refactoring now, actually, as this type of confusion about where code is designed to be executed is a _really_ common thing I see reported, and has lead to a series of monkey-patches and hacks.  Note that none of these changes will ever make a `WalletConnectedAccount` object work in the nodejs context, because the _only way this object can function is by changing `window.location` in a browser context_.

**Comment by ryancwalsh** [comment]
@MaximusHaximus Great points! Thanks!

**Comment by ryancwalsh** [comment]
Hey @MaximusHaximus , I'm curious whether you or anyone has made progress in the direction that you described above.  Where can I track that?

If not, can you please reopen https://github.com/near/near-api-js/issues/747 because I keep running into this problem.

Thanks!

**Pull request closed without merging**
