### PR TITLE
more allowances in test

### PR DESCRIPTION
**Pull request by bowenwang1996**
Add more allowances to access key in test to make it work with https://github.com/nearprotocol/nearcore/pull/3028

### CODE REVIEW

**Comment by chadoh** [comment]
Are the test failures legit?

**Comment by vgrichina** [comment]
@bowenwang1996 we need to change default attached gas I think as well, as we won't be giving 2 NEAR allowances in wallet (that is too much).

**Comment by bowenwang1996** [comment]
@chadoh I think it is just flaky.

**Comment by bowenwang1996** [comment]
@vgrichina sure. What do you want to change it to? Also that can be done in a separate PR

**Comment by bowenwang1996** [comment]
I'll merge this to unblock the nearcore PR

**Pull request merged**
