### PR TITLE
fix: remove never used variables

### PR DESCRIPTION
**Pull request by BogdanovBogdan**
## Description
Fixed linter bugs, like as variable _is assigned a value but never used_

## Checklist
- [x] Read the [contributing](https://github.com/near/near-api-js/blob/master/CONTRIBUTING.md) guidelines
- [x] Commit messages follow the [conventional commits](https://www.conventionalcommits.org/) spec
- [x] Performed a self-review of the PR
- [ ] Added automated tests
- [x] Manually tested the change

### CODE REVIEW

**Comment by hcho112** [comment]
LGTM, just wondering, do we need to remove this?
https://github.com/near/near-api-js/blob/dab149c54c757e75094ac256f187346d497ea926/.github/dependabot.yml#L22

**Comment by morgsmccauley** [comment]
> LGTM, just wondering, do we need to remove this?
> 
> https://github.com/near/near-api-js/blob/dab149c54c757e75094ac256f187346d497ea926/.github/dependabot.yml#L22

Yes we do, good catch.

**Review by hcho112 — APPROVED** [review]
LGTM

**Comment by morgsmccauley** [comment]
Thanks @BogdanovBogdan!

**Pull request merged**
