### PR TITLE
fix: don't use window in `new WalletConnection`

### PR DESCRIPTION
**Pull request by chadoh**
Quick workaround to address https://github.com/near/near-api-js/issues/747 until the larger https://github.com/near/near-api-js/pull/748 is dealt with

### CODE REVIEW

**Comment by chadoh** [comment]
You can see that this works here: https://github.com/AhaLabs/tenk-template-gatsby/commit/bdfd70d148bb9826e734f141cd964a89617c9284

This can be used now by updating your `package.json` with:

    "near-api-js": "AhaLabs/near-api-js#1.0.1"

**Comment by chadoh** [comment]
Not stale!

**Review by volovyk-s — APPROVED** [review]

**Comment by volovyk-s** [comment]
@MaximusHaximus I think we can merge such a fix since we are not working on a better resolution now.

**Comment by chadoh** [comment]
Not stale

**Comment by chadoh** [comment]
this stale bot is a pain

**Comment by chadoh** [comment]
🥇

**Comment by chadoh** [comment]
Nooooooo

**Comment by agileurbanite** [comment]
@gutsyphilip @andy-haynes can you take a look at this PR?

**Comment by esaminu** [comment]
@agileurbanite @MaximusHaximus can this wait until we publish a `near-api-nodejs` package shortly that can be used in the server context? I think the user needs to be alerted of these issues as early as possible (i.e. when importing) rather than when using something. Also, making the current package 'safe' to import on the server context will involve applying this pattern in many other places including `BrowserLocalStorageKeyStore` among others. 

For the purposes of SSR, like in Gatsby and Next.js I believe these issues can be addressed using dynamic imports like suggested [here](https://www.gatsbyjs.com/docs/using-client-side-only-packages/#workaround-3-use-reactlazy-and-suspense-on-client-side-only) for example so that parts of the app that require use of the current package or the future `near-api-browser` are only invoked on the client side. Users implementing SSR will have to keep dynamically importing the browser package after we create a server side package if they would like to request login or signing of a transaction from a wallet.

**Comment by chadoh** [comment]
I understand this approach is not perfect but it's small and safe and fixes some important use cases. Why not merge it.

**Comment by chadoh** [comment]
Like, you can merge this now and do the bigger better thing later.

**Comment by ryancwalsh** [comment]
I agree. There have been so many people reporting this problem since Dec 2021 or earlier, and near-api-js has never been updated to address it.  cc @agileurbanite

**Comment by esaminu** [comment]
Created a proposed solution in #896 . I think there's a genuine complaint here about devX in SSR stacks, we just have to balance that out with the behavior in Node.js as well

**Comment by esaminu** [comment]
Fixed in #896 Thanks guys! 🙂

**Pull request closed without merging**
