### PR TITLE
fix: fix AccessKeyInfoView type

### PR DESCRIPTION
**Pull request by raymondfeng**
The 'public_key' should be a string

Signed-off-by: Raymond Feng <enjoyjava@gmail.com>

### CODE REVIEW

**Comment by mehtaphysical** [comment]
Looks good. Just need to fix the `view account details after adding access keys` test.

**Comment by raymondfeng** [comment]
Pushed a fix

**Comment by mehtaphysical** [comment]
looks good to me.

**Comment by volovyk-s** [comment]
@mehtaphysical Ok, this refactoring is out of scope.

**Review by volovyk-s — APPROVED** [review]

**Pull request merged**
