### PR TITLE
fix: disable internal logging with env variable

### PR DESCRIPTION
**Pull request by willemneal**
'NEAR_NO_LOGS ' is used to disable printing internal logs  and errors.

### CODE REVIEW

**Comment by willemneal** [comment]
@volovyk-s It's not running CI.  Do I need a different role to start the CI?

**Comment by volovyk-s** [comment]
@willemneal also noticed that, trying to find the reason

**Review by chadoh — APPROVED** [review]
This works in NodeJS, but does not give browser environments an easy way to opt-in (at least not on-the-fly, without rebuilding & redeploying). Maybe that's a good thing, though.

**Comment by volovyk-s** [comment]
@willemneal looks like it's a problem with GitHub: 
image
I will double-check if it will not be solved by tomorrow.

**Comment by willemneal** [comment]
> This works in NodeJS, but does not give browser environments an easy way to opt-in (at least not on-the-fly, without rebuilding & redeploying). Maybe that's a good thing, though.

Yeah I figure that console logs in browser aren't a huge deal.  Also they can mock `process` with a bundler.

**Comment by willemneal** [comment]
@volovyk-s no rush, just wanted to get this in before a release since it will make our test output much cleaner.

**Comment by chadoh** [comment]
Might want to check with strongly opinionated folks who might prefer that
we keep this change backwards-compatible. We could make it so verbose
logging is on by default, with an environment variable flag to turn it off.

**Comment by willemneal** [comment]
@chadoh  It should be backwards compatible.  I didn't have to change the test setup, which uses the logs.

**Comment by chadoh** [comment]
It’s not backwards compatible. Logs now need to be opted into by dependent projects. Previously they were always on.

We could make the environment variable something like `NODE_NO_LOGS`, like your description says, instead of `NEAR_PRINT_LOGS`, which is currently used in the code here.

**Comment by willemneal** [comment]
@chadoh My bad I hadn't pushed my changes that did exactly as you mention.  Also adding more now to suppress warnings too.

**Review by chadoh — APPROVED** [review]

**Review by volovyk-s — APPROVED** [review]

**Pull request merged**
