### PR TITLE
feat: update RPC error schema for protocol version 69

### LINKED ISSUE #1358: Updating RPC error schema
### Description

With the upcoming release of stateless validation in Near Protocol, there are new errors a RPC node may return when a transaction is submitted. Notably, [`ShardCongested`](https://github.com/near/docs/pull/2018), [`ShardStuck`](https://github.com/near/docs/pull/2120), and `ReceiptSizeExceeded`. These are about to land on testnet this week and will make it into mainnet, hopefully within 5-6 weeks.

I wanted to updated the error schema to include them. But I don't get how exactly this should work. Especially how to update `packages/near-api-js/src/generated/rpc_error_schema.json`. 

In the main Readme, there is this description:

```
### Update error schema

Follow next steps:

1. [Change hash for the commit with errors in the nearcore](https://github.com/near/near-api-js/blob/master/packages/utils/fetch_error_schema.js#L8-L9)
2. Fetch new schema: `node fetch_error_schema.js`
3. `pnpm build` to update `lib/**.js` files
```

Step 1 seems outdated, since the linked line already points to master instead of a specific commit. Also, the path has changed. (I can send a fix PR but first need to understand what the correct process is)
Step 2 works and updates the file in `packages/utils/src/errors/rpc_error_schema.json` as expected with the new error variants.
Step 3 succeeds but doesn't update anything for me.

After these steps, I have an updated `packages/utils/src/errors/rpc_error_schema.json` but my `packages/near-api-js/src/generated/rpc_error_schema.json` file still contains the old schema without new errors. Since this is in the `generated` folder, I assume there must be a script that updates it. But it looks to me like this is a different format, perhaps just an old format.

Can someone help me figure out how to update the error schema fully, including `packages/near-api-js/src/generated/rpc_error_schema.json`?

### PR DESCRIPTION
**Pull request by jakmeier**
With protocol version 68, cross-shard congestion control is introduced that adds two new errors on the RPC endpoints for submitting transactions. (ShardCongested, ShardStuck)

Protocol version 69 introduces stateless validation and also adds a new error for submitted transactions. (ReceiptSizeExceeded)

Technically, there are additional errors in nearcore's version of the rpc schema. But those are from nightly features that have not been masked properly. (NonRefundableTransferToExistingAccount  and InvalidTransactionVersion are waiting for NEP-491 and NEP-541 respectively.)

Aside from updating the schema, I also added human readable error messages and tests for the new errors.

Closes #1358

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/near/near-api-js/blob/master/CONTRIBUTING.md).
- [x] Commit messages follow the [conventional commits](https://www.conventionalcommits.org/) spec
- [x] **If this is a code change**: I have written unit tests.
- [x] **If this changes code in a published package**: I have run `pnpm changeset` to create a `changeset` JSON document appropriate for this change.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

See #1358 

## Test Plan

Unit tests in `packages/utils/test/rpc-errors.test.js` check that the new error kinds are recognized as expected.

## Related issues/PRs

See #1358

### CODE REVIEW

**Comment by jakmeier** [comment]
I've only added a minor bump changeset for the utils package, since I only changed code in there. If this isn't right, please let me know which packages should be included.

**Comment by jakmeier** [comment]
@race-of-sloths please, include my PR in the race

**Comment by race-of-sloths** [comment]
@jakmeier Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
New Sloth joined the Race! Welcome!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/jakmeier?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/jakmeier?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/jakmeier)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/jakmeier)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by jakmeier** [comment]
@mpeterdev @andy-haynes can one of you please review this PR? Vlad pinged you in the Telegram Tools Communiy Group last weak but you might have missed that.

**Comment by andy-haynes** [comment]
Thanks @jakmeier for the clear description! Changeset looks good, much appreciated.

**Comment by andy-haynes** [comment]
@race-of-sloths score 3

**Comment by race-of-sloths** [comment]
### 🌟 Score recorded!

@andy-haynes, thank you for scoring this pull request in the Race of Sloths!

**Review by andy-haynes — APPROVED** [review]

**Comment by race-of-sloths** [comment]
### ✅ PR is finalized! 
Your contribution is much appreciated with a final score of 3!
You have received 40 (30 base + 10 weekly bonus) Sloth points for this contribution


Another weekly streak completed, well done @jakmeier! To keep your weekly streak and get another bonus make pull request next week! Looking forward to see you in race-of-sloths

**Pull request merged**
