### PR TITLE
Add more documentation and clean up code

### PR DESCRIPTION
**Pull request by willemneal**

### CODE REVIEW

**Comment by vgrichina** [comment]
@willemneal is this ready for review? Asking as you haven't added reviewers but it's not a draft.

**Comment by willemneal** [comment]
Sorry meant to be a draft as we will make PRs to this branch as we work on documentation.

Though I would like an initial review

**Comment by vgrichina** [comment]
> Sorry meant to be a draft as we will make PRs to this branch as we work on documentation.

I'd prefer PRs

**Comment by vgrichina** [comment]
> Sorry meant to be a draft as we will make PRs to this branch as we work on documentation.

@willemneal @mikedotexe @janedegtiareva I kinda feel it's actually best to merge small PRs as soon as possible, otherwise merging this branch will be life of pain given that changes are likely to touch every single source file.

**Comment by mikedotexe** [comment]
ah, I thought we were going to merge this Monday after we verified the other branches are ready. We're trying to have this ready by Tuesday.
Now I'm scrambling to fix all the broken links in docs. #lifeofpain

**Pull request merged**
