### PR TITLE
Fix/contract callback url ignored

### LINKED ISSUE #520: callbackUrl support is broken
**Is your feature request related to a problem? Please describe.**

I've been trying to work out how to use the Near Wallet's callbackUrl query arg, to pass my Near app's state across the wallet transaction without writing to the blockchain or local storage.  walletConnection.requestSignTransaction() has a callbackUrl argument specifically to support this.  But the only caller of that method is walletConnection.signAndSendTransaction(), which only allows the callbackUrl to be window.location.href, thereby blocking use of this feature.

**Describe the solution you'd like**

One solution would be for the autogenerated contract methods on the contract object to accept an optional extra options argument -- an object which could specify callbackUrl or other useful things in the future.

**Describe alternatives you've considered**

I can try to hack/patch this in myself and send a pull req, if this is a desired feature.  But if this is deprecated, if there's some other preferable approach to the problem of passing client state through a Near wallet transaction, please point me at it.  Thanks!

**Additional context**

http://beta.plantary.art -- after purchase of an NFT we want to redirect the user to the link for that NFT.

### PR DESCRIPTION
**Pull request by mehtaphysical**
Fixes #520

Here is a proposed fix for `callbackUrl` and adding `meta`.

### CODE REVIEW

**Comment by mehtaphysical** [comment]
@vgrichina how does this look?

**Comment by mehtaphysical** [comment]
Also fixes #419

**Comment by mehtaphysical** [comment]
bump @vgrichina @mikedotexe @thisisjoshford

**Comment by thisisjoshford** [comment]
> bump @vgrichina @mikedotexe @thisisjoshford

going to defer to @vgrichina and @mikedotexe on this one :)

**Review by volovyk-s — APPROVED** [review]

**Pull request merged**
