### PR TITLE
Error polyfill deletion

### PR DESCRIPTION
**Pull request by volovyk-s**
@MaximusHaximus we are having some troubles with this dependency, do we still need it in the wallet? Looks like it's not used in `near-api-js` internally.
Details here: https://github.com/near/near-api-js/issues/593

### CODE REVIEW

**Comment by MaximusHaximus** [comment]
@volovyk-s thanks for the heads up -- I did some digging through git history and discovered that this polyfill exists due to usage of `error.captureStackStrace()` inside of the `http-errors` package, which is a package made explicitly for nodeJS  usage (thus the captureStackTrace() usage...), used for composing http errors (basically, errors with `status`/`statusCode` properties, but also some other API details around attaching custom properties).

Here's the problem in a nutshell:
https://github.com/jshttp/http-errors/issues/28

All that we currently use from `http-errors` _directly_ in the wallet and `near-api-js` is the `createError()` method, which we could replace with our own implementation with guarding around the `captureStackTrace()` functionality for backwards compat for browsers.  We use the _simplest_ form of `createError()`, so all we are really getting is the equivalent of creating an error and setting `code` and `statusCode` properties on it in one call.

There's even mention of doing this in this (sadly, closed) issue:
https://github.com/near/near-api-js/issues/119

it's worth nothing that both `near-wallet` and `near-api-js` also require `http-errors` dependency _indirectly_, by way of `fetch-send-json` package as well, which is a simple wrapper around fetch that we also own (https://github.com/near/send-json).

Since we want `near-api-js` to be browser-friendly, and it's clear from the issue I linked above that `http-errors` package does not intend to add compatibility for browsers (or react native -- see https://github.com/jshttp/http-errors/issues/74 also), I think it makes sense for us to have a browser-friendly version of `http-errors` that wraps the `captureStackTrace()` logic for older browsers.

However, `error-polyfill` does do some formatting/parsing of stack traces inside of its provided `captureStackTrace()` method, so removing this could negatively effect our stack trace content in older browsers if I am reading the code therein correctly.

**Most importantly, by removing this polyfill, we probably broke old browsers being able to use the `near-api-js` since we still have the dependency on `http-errors` present.**

**Review by MaximusHaximus — CHANGES_REQUESTED** [review]
Comment added by mistake instead of review :)

**Comment by vgrichina** [comment]
@volovyk-s +1 to @MaximusHaximus comments, it's not about wallet, but about browser support

note that it doesn't seem hard to remove http-errors dependency from all of these packages (they are all ours) but it has to happen before removing polyfill

**Comment by volovyk-s** [comment]
@MaximusHaximus thanks for a detailed answer!
@vgrichina ok, sounds like a plan. Meanwhile, I'm converting this PR to `Draft`. 
@mikedotexe  I would say that we should prioritize this issue since it creates problems for developers.

**Pull request closed without merging**
