### PR TITLE
Update to typescript 4.2

### PR DESCRIPTION
**Pull request by mehtaphysical**
Seems like this is relatively safe. Not `.d.ts` files change after this update.

### CODE REVIEW

**Comment by vgrichina** [comment]
@mehtaphysical looks like the only concern here is users who themselves use older version of TypeScript with near-api-js. This has previously caused some problems, so just wanna make sure it's on your radar.

**Comment by volovyk-s** [comment]
@mehtaphysical let's postpone this merge for a few months, there is some breaking changes in this version: https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#breaking-changes
We should give developers time to upgrade their TS version first

**Comment by mikedotexe** [comment]
Put a calendar event for us to revisit in a month.

**Comment by volovyk-s** [comment]
@mehtaphysical @mikedotexe month has passed.

**Comment by volovyk-s** [comment]
@mehtaphysical let's fix conflicts here and merge this PR.

**Pull request closed without merging**
