### PR TITLE
fixed broken tests

### PR DESCRIPTION
**Pull request by chefsale**

### CODE REVIEW

**Comment by chefsale** [comment]
Tested the local version used in the nearcore CI:
```
JsonRpcProvider.block(blockId) deprecated use `block({ blockId })` or `block({ finality })` instead test/providers.test.js:164:32
 PASS  test/providers.test.js
  ● Console

    console.log
      Loaded master account test.near key from /home/sandi/workspace/near/nearcore/scripts/../testdir/.near/validator_key.json with public key = ed25519:22skMptHjFWNyuEWY22ftn2AbLPSYpmYwGJRGwpNHbTV

      at Object.connect (lib/near.js:96:25)

    console.log
      Loaded master account test.near key from /home/sandi/workspace/near/nearcore/scripts/../testdir/.near/validator_key.json with public key = ed25519:22skMptHjFWNyuEWY22ftn2AbLPSYpmYwGJRGwpNHbTV

      at Object.connect (lib/near.js:96:25)


 PASS  test/wallet-account.test.js
 PASS  test/key_stores/merge_keystore.test.js
 PASS  test/key_pair.test.js
 PASS  test/serialize.test.js
 PASS  test/key_stores/unencrypted_file_system_keystore.test.js
 PASS  test/key_stores/in_memory_keystore.test.js
 PASS  test/key_stores/browser_keystore.test.js
 PASS  test/utils/format.test.js
 PASS  test/validator.test.js
 PASS  test/utils/rpc-errors.test.js
 PASS  test/signer.test.js
 PASS  test/contract.test.js
 PASS  test/transaction.test.js
--------------------------------------|---------|----------|---------|---------|------------------------------------------------------------------------------
File                                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                            
--------------------------------------|---------|----------|---------|---------|------------------------------------------------------------------------------
All files                             |   85.73 |    72.28 |   84.57 |   87.35 |                                                                              
 lib                                  |    84.1 |    75.75 |   83.59 |   85.71 |                                                                              
  account.js                          |   78.63 |       76 |   88.89 |   78.63 | 95-99,103,108-114,118,136,149,165,209,256,261,264,291,321-328                
  account_creator.js                  |   71.43 |      100 |      50 |   71.43 | 30-42                                                                        
  common-index.js                     |   66.67 |    51.85 |   43.75 |   76.74 | 3-7,10-12,16-19                                                              
  connection.js                       |   78.95 |    33.33 |     100 |   78.95 | 13,15,25,29                                                                  
  contract.js                         |     100 |    95.83 |     100 |     100 | 3                                                                            
  index.js                            |   57.14 |    61.76 |   57.14 |   57.89 | 6-7,10-12,16-19                                                              
  near.js                             |   70.21 |    67.86 |   57.14 |   70.21 | 28-42,51,62-75,100                                                           
  signer.js                           |      96 |    84.62 |     100 |      96 | 56                                                                           
  transaction.js                      |     100 |    92.31 |     100 |     100 | 3                                                                            
  validators.js                       |     100 |    93.33 |     100 |     100 | 3                                                                            
  wallet-account.js                   |   93.69 |    83.33 |   94.44 |   93.64 | 59,126-127,163-167,208                                                       
 lib/generated                        |     100 |      100 |     100 |     100 |                                                                              
  rpc_error_types.js                  |     100 |      100 |     100 |     100 |                                                                              
 lib/key_stores                       |   94.67 |    76.92 |      90 |   95.09 |                                                                              
  browser_local_storage_key_store.js  |   97.14 |    66.67 |   88.89 |   97.06 | 41                                                                           
  in_memory_key_store.js              |     100 |      100 |     100 |     100 |                                                                              
  index.js                            |   94.12 |      100 |      80 |     100 |                                                                              
  keystore.js                         |     100 |      100 |     100 |     100 |                                                                              
  merge_key_store.js                  |   92.59 |      100 |    87.5 |   92.59 | 46-47                                                                        
  unencrypted_file_system_keystore.js |    91.8 |    76.19 |   88.89 |    91.8 | 14-15,36-37,131                                                              
 lib/providers                        |   84.04 |    78.38 |   70.37 |   87.21 |                                                                              
  index.js                            |   81.25 |      100 |      50 |     100 |                                                                              
  json-rpc-provider.js                |   79.25 |       72 |   68.75 |   80.39 | 27,58,108-118,142-147,155                                                    
  provider.js                         |      96 |    91.67 |     100 |      96 | 39                                                                           
 lib/utils                            |   81.82 |    69.93 |   84.47 |    83.6 |                                                                              
  enums.js                            |   90.91 |       50 |     100 |   90.91 | 7                                                                            
  errors.js                           |   91.67 |      100 |      75 |   91.67 | 26                                                                           
  exponential-backoff.js              |   57.14 |       50 |   33.33 |   58.33 | 11-15,20                                                                     
  format.js                           |     100 |    91.67 |     100 |     100 | 3,35                                                                         
  index.js                            |   63.64 |    51.85 |   44.44 |   70.59 | 3-7,10-12,16-19                                                              
  key_pair.js                         |      86 |    70.37 |     100 |      86 | 18,24,46,62,68,73-77                                                         
  network.js                          |     100 |      100 |     100 |     100 |                                                                              
  rpc_errors.js                       |   79.37 |    72.73 |   76.92 |   83.33 | 6-7,10-12,16-19,47                                                           
  serialize.js                        |   83.74 |       70 |   88.37 |   84.49 | 6-7,12,52-59,126-132,161,175,221,241,249-252,258,277,302-305,311,323,329,336 
  web.js                              |   74.42 |    62.96 |     100 |   74.42 | 28,41,54-58,63-67,71                                                         
 test                                 |   75.68 |    27.78 |     100 |   77.78 |                                                                              
  config.js                           |   33.33 |       10 |     100 |   33.33 | 5-21,36-48                                                                   
  test-utils.js                       |   89.29 |       50 |     100 |   92.59 | 19,58                                                                        
 test/key_stores                      |     100 |      100 |     100 |     100 |                                                                              
  keystore_common.js                  |     100 |      100 |     100 |     100 |                                                                              
--------------------------------------|---------|----------|---------|---------|------------------------------------------------------------------------------

Test Suites: 17 passed, 17 total
Tests:       141 passed, 141 total
Snapshots:   0 total
Time:        61.233 s
Ran all test suites matching /test/i.
Done in 68.45s.
+ yarn doc
yarn run v1.22.5
$ typedoc src && touch docs/.nojekyll

Using TypeScript 3.9.7 from /home/sandi/workspace/near/n
```

**Comment by chefsale** [comment]
Tests on travis pass as well. I think we should make sure that we test all  the NODE_ENV and move to buildkite.

**Review by frol — APPROVED** [review]
It is fine, though I fail to assess whether it is a proper fix (maybe we should change the env configuration instead of patching it down the line?)

**Comment by chefsale** [comment]
Yes, I don't have enough context to do that, but will leave it to @vgrichina and discuss with him, also I believe we should move all this testing to buildkite and create a testing for all the envs and that would also give us ability to easily kickoff them through buildkite as well.

**Pull request merged**
