### PR TITLE
Naj 44 make sign and send transaction functionality public

### PR DESCRIPTION
**Pull request by AbdulBaseerKhan**
## Motivation
NAJ-44

## Description
`signAndSendBundledActions` methods added to expose the functionality of `protected signAndSendTransaction`

## Checklist
- [x] Read the [contributing](https://github.com/near/near-api-js/blob/master/CONTRIBUTING.md) guidelines
- [x] Commit messages follow the [conventional commits](https://www.conventionalcommits.org/) spec
- [x] Performed a self-review of the PR
- [x] Added automated tests
- [x] Manually tested the change

### CODE REVIEW

**Comment by esaminu** [comment]
@AbdulBaseerKhan We have examples in the cookbook and tests that use `signAndSendTransaction` in the way you are describing e.g. [batch-transactions.js](https://github.com/near/near-api-js/blob/master/examples/cookbook/transactions/batch-transactions.js). Why don't we just remove the access modifier and make this public.

**Comment by AbdulBaseerKhan** [comment]
> @AbdulBaseerKhan We have examples in the cookbook and tests that use `signAndSendTransaction` in the way you are describing e.g. [batch-transactions.js](https://github.com/near/near-api-js/blob/master/examples/cookbook/transactions/batch-transactions.js). Why don't we just remove the access modifier and make this public.

@esaminu It was mentioned in the ticket (NAJ-44) that do not make that method public. Write another method instead and will updated the documentations accordingly.

**Comment by esaminu** [comment]
@AbdulBaseerKhan I saw that but I'm wondering whether there's any specific reason not to. I found this discussion from the reported issue https://github.com/near/near-api-js/pull/557#discussion_r624559026 that came to the same conclusion. Also can you review that PR, Maybe it has other stuff we want as well?

**Comment by esaminu** [comment]
Closing in favor of #1002

**Pull request closed without merging**
