### PR TITLE
feat: create transaction builder class

### PR DESCRIPTION
**Pull request by willemneal**
Reoppening of #793

### CODE REVIEW

**Comment by esaminu** [comment]
Thanks for this @willemneal! We should add tests of the new Builder class. Also, would this fit better as it's own module i.e. `src/transactionBuilder.ts`?

**Comment by willemneal** [comment]
The circular dependency with Account lead me to keep them together.  Perhaps when refactoring NAJ we can use an interface for signer and `{ accountId: string}`. 

As a note, I've been using this personally and can vouch for it's correctness, but will add some tests.

**Comment by esaminu** [comment]
Thanks! we'll keep this refactor in mind for the upcoming package separation work 👍 

Yeah I think tests would be great here to ensure future change sets to either class don't break this 🙂

**Comment by willemneal** [comment]
@esaminu Added example and test

**Comment by esaminu** [comment]
I rebased and fixed lint errors in [feat/tx_class](https://github.com/near/near-api-js/tree/feat/tx_class). We should push that to this PR and re review

**Comment by esaminu** [comment]
Closing in favor of #998

**Pull request closed without merging**
