### PR TITLE
use block_id in rpc query

### LINKED ISSUE #635: RpcQueryRequest expects and sends `blockId` but RPC node expects `block_id`
**Describe the bug**

This code conforms to the TypeScript typings, and the library has no problem sending it off:

```ts
await near.connection.provider.query({
  request_type: 'view_account',
  account_id: 'nectar.near',
  blockId: 40258947,
});
```

But the RPC node expects `block_id` instead of `blockId` and breaks.

[Possibly related](https://github.com/near/near-api-js/blob/c5762ea30119a2966505afaec132a39f19d623a1/lib/providers/provider.d.ts#L29)

**To Reproduce**

```ts
const near = await connect({
  networkId: 'mainnet',
  keyStore: new keyStores.BrowserLocalStorageKeyStore(),
  nodeUrl: 'https://archival-rpc.mainnet.near.org', // using archival RPC so that I can request a specific block ID
  walletUrl: 'https://wallet.mainnet.near.org',
  helperUrl: 'https://helper.mainnet.near.org',
});

await near.connection.provider.query({
  request_type: 'view_account',
  account_id: 'nectar.near',
  blockId: 40258947,
});
```

Generated request:

```json
{
    "method": "query",
    "params": {
        "request_type": "view_account",
        "account_id": "nectar.near",
        "blockId": 40258947
    },
    "id": 125,
    "jsonrpc": "2.0"
}
```

Response:

```json
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid params",
        "data": "Failed parsing args: no variant of enum BlockReference found in flattened data"
    },
    "id": 125
}
```

**Expected behavior**

Either the library expects `block_id` or it remaps `blockId` to `block_id` such that generated request is:

```json
{
    "method": "query",
    "params": {
        "request_type": "view_account",
        "account_id": "nectar.near",
        "block_id": 40258947
    },
    "id": 125,
    "jsonrpc": "2.0"
}
```

Response:
```json
{
    "jsonrpc": "2.0",
    "result": {
        "amount": "19916070150000000000000",
        "locked": "0",
        "code_hash": "11111111111111111111111111111111",
        "storage_usage": 346,
        "storage_paid_at": 0,
        "block_height": 40258947,
        "block_hash": "HxdYhKTs44Huyg7gZkMoUxVW6xHP2j1BfQeBroHtGeTx"
    },
    "id": 125
}
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 Build 19042.1081
 - `near-api-js` version 0.41.0

**Additional context**
I am connecting to an archival RPC node.

### PR DESCRIPTION
**Pull request by mehtaphysical**
Fixes #635

### CODE REVIEW

**Review by volovyk-s — APPROVED** [review]
@mehtaphysical LGTM
Don't forget to run `yarn build` before the merge.

**Comment by mehtaphysical** [comment]
> @mehtaphysical LGTM
> Don't forget to run `yarn build` before the merge.

Thanks!! :)

**Comment by volovyk-s** [comment]
@thisisjoshford @mikedotexe we need one more review here.

**Review by thisisjoshford — APPROVED** [review]
LGTM! Thanks for adding a test too! 💪🏼

**Pull request merged**
