### PR TITLE
Fixed wrong blockId field in BlockReference type

### PR DESCRIPTION
**Pull request by erditkurteshiSQA**
Closes issue #844

### CODE REVIEW

**Comment by esaminu** [comment]
@erditkurteshiSQA @janewang is there a reason to make this change? This is a non backwards compatible change and we have [tests](https://github.com/near/near-api-js/blob/master/test/providers.test.js#L89) that indicate this works just fine with the snake case parameter. Also it seems there are other places in the code that rely on this parameter being `block_id`

**Comment by erditkurteshiSQA** [comment]
@esaminu Thank you for reviewing the PR, 
I tested it again with the latest version and I am getting the same error with this code.
``` ts
   const viewState = await provider.query<ViewStateResult>({
      request_type: "view_state",
      blockId: 95874000,
      account_id: "kurteshierdit.testnet",
      prefix_base64: Buffer.from("STATE", "utf-8").toString("base64"),
    });
```
Can you confirm that this code is working for you?

**Comment by esaminu** [comment]
AFAICT these methods depend on the param being `blockId` :

- JsonRpcProvider.block
- JsonRpcProvider.blockChanges
- JsonRpcProvider.accessKeyChanges
- JsonRpcProvider.singleAccessKeyChanges
- JsonRpcProvider.accountChanges
- JsonRpcProvider.contractStateChanges
- JsonRpcProvider.contractCodeChanges

These methods depend on the param being `block_id`:

- JsonRpcProvider.experimental_protocolConfig
- JsonRpcProvider.query

Decision was to change the implementation for the last two and mark the next release as a breaking change 👍 

cc @janewang

**Comment by erditkurteshiSQA** [comment]
The error in the `JsonRpcProvider.query` method was fixed by these 2 commits (PRs):
The logic for accepting `block_id` or `blockId` in the query method was fixed here
https://github.com/near/near-api-js/commit/91d9b764c968f05e87b0b230f8b389035885f97f

The reason this error **"Parse error: Failed parsing args: no variant of enum BlockReference found in flattened data"** was
showing is because the errors were not handled correctly at the time this issue was reported but they were fixed here:
https://github.com/near/near-api-js/pull/910/commits/3ad619d44f360a33275b997b80397d9b74465b6e

There's no need to change the type for `JsonRpcProvider.experimental_protocolConfig` to `blockId` because it already accepts `blockId` as a param, I think the issue here is because the `sendJsonRpc` method will always wait for a `block_id` param.

The fix for this without including a breaking change can be made by adding a workaround which is present in all other methods.
Something like:
```ts
const { blockId, ...otherParams } = blockReference as any;
```
And then when we call the `sendJsonRpc` we do something like this:
```ts
return await this.sendJsonRpc('EXPERIMENTAL_protocol_config', { ...otherParams, block_id:  blockId });
```

This PR will be closed to another PR because there are too many conflicts in the current branch: https://github.com/near/near-api-js/pull/969

**Comment by esaminu** [comment]
@erditkurteshiSQA Yes, the TS `BlockReference` type is enforcing that the `blockId` field should be camel case so the user would get typescript errors if they try to pass in the snake case `block_id`. The only place that currently accepts both in the implementation is the `query` method and it has an `any` type. We need to update `experimental_protocolConfig` implementation to take in `blockId` instead of `block_id` as you outlined. This is a breaking change though because people that were calling `experimental_protocolConfig` with `block_id` will now not have that forwarded to `sendJsonRpc`. We could consider this a fix since people passing in `block_id` were doing so despite the type signature being incorrect.

**Comment by esaminu** [comment]
@erditkurteshiSQA Yes, the TS `BlockReference` type is enforcing that the `blockId` field should be camel case so the user would get typescript errors if they try to pass in the snake case `block_id`. The only place that currently accepts both in the implementation is the `query` method and it has an `any` type. We need to update `experimental_protocolConfig` implementation to take in `blockId` instead of `block_id` as you outlined. This is a breaking change though because people that were calling `experimental_protocolConfig` with `block_id` will now not have that forwarded to `sendJsonRpc`. We have a test that [passes in `block_id`](https://github.com/near/near-api-js/blob/master/packages/near-api-js/test/providers.test.js#L302) that will fail after this change. 

We could consider this a fix since people passing in `block_id` were doing so despite the type signature being incorrect.

**Comment by esaminu** [comment]
Closed in favor of #969

**Pull request closed without merging**
